//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserReg1Entities : DbContext
    {
        public UserReg1Entities()
            : base("name=UserReg1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CreditCardRequests> tbl_CreditCardRequests { get; set; }
        public virtual DbSet<tbl_WebsiteUsers> tbl_WebsiteUsers { get; set; }
    }
}
