//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CreditCardRequests
    {
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public string RequestedCardType { get; set; }
    
        public virtual tbl_WebsiteUsers tbl_WebsiteUsers { get; set; }
    }
}
